### ISSUE TITLE
Is the data available as a AWS RDS snapshot? If not, is there any way to create one?

### ISSUE THREAD

**Issue by sujitsagar** [openaq/openaq-data-format#22]

**Comment by sruti** [comment]
Hi @sujitsagar! Great question,  we did have regularly updated public RDS snapshots available until a couple months ago but you are the first person to ask about it so we didn't move over that functionality when we upgraded the database. I just created one called `openaq-latest`. Hope that works!

**Comment by sujitsagar** [comment]
Hi Sruti,

Thanks for creating the snapshot. I am trying to build machine learning models on the top of `open-aq` data. Having the data in a database format definitely makes it easier to convert it into required format.

But, I couldn't find RDS public snapshot with the name `openaq-latest` in AWS N.Virginia region. Can you please give me snapshot id?

**Comment by sruti** [comment]
That's because I forgot to make it public. Should be able to find it now! Very cool, you should join our Slack, I know a few others in the community are working on machine learning models as well.

**Comment by sujitsagar** [comment]
Thanks, Sruti. I am able to access the snapshot now. Is it going to be frequently updated with latest data?

Also, joined the Slack group. Thanks for the invitation. Excited to be part of it.
