### ISSUE TITLE
Adding in two properites to the data format - feedback sought

### ISSUE THREAD

**Issue by RocketD0g** [openaq/openaq-data-format#8]
Because the [SPARTAN data](http://spartan-network.org/) is research-grade and not data created by/on behalf of a governmental body - like all other data in our system to date, adding new properties to our data format will be necessary before we add the SPARTAN data to the system (PR [here](https://github.com/openaq/openaq-fetch/pull/173))

Thoughts/feedback on this structure? cc: @dolugen @olafveerman  @jflasher 

**Additional Tag # 1:** 
sourceType - This delineates what data source type from which the data originates:

- **Type 1** - Sensors that are deployed by citizen scientists, often low-cost sensors.
- **Type 2** - Sensors that are deployed by researchers affiliated with universities and/or research     organizations.
- **Type 3** - Sensors that are deployed by or on behalf of governmental bodies. 

**Additional Tag # 2:** 
mobile - This is either T/F, and indicates whether the source is stationary or mobile.

**Comment by jflasher** [comment]
I like these. For `sourceType` I guess I'd rather it be descriptive like `government`, `research` and something else, but I'm really not sure what the best words would be for those. So perhaps just having them be arbitrary type numbers works fine. I guess anything that's searchable is what's really needed.

**Comment by RocketD0g** [comment]
I'm fine with `government` and `research`, as well, but what's a good suggestion for the third type, then? It's a bit of a catch all else. I don't particularly like `public` or   `lowcostsensor`.

**Comment by olafveerman** [comment]
I agree with you on the `lowcostsensor`. That gets into the type of sensor used, not the type of organization.

If it's a catch-all, why not call it `other` or `misc`?

**Comment by RocketD0g** [comment]
Yeah, I think `other` sounds fine.

**Comment by jflasher** [comment]
Added in now!
